"""add connectivity tables

Revision ID: 24234028c814
Revises:
Create Date: 2026-06-17 15:21:11.966189

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_identity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('kubernetes_version', sa.String(length=64), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('namespace_count', sa.Integer(), nullable=True),
    sa.Column(
        'registered_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column(
        'last_seen_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('api_url', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heartbeat_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column(
        'sent_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heartbeat_record')
    op.drop_table('credentials')
    op.drop_table('cluster_identity')
    # ### end Alembic commands ###
