"""add incident table

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-18 17:25:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', create_type=False), nullable=False),
    sa.Column('namespace', sa.String(length=253), nullable=False),
    sa.Column('resource_kind', sa.String(length=64), nullable=False),
    sa.Column('resource_name', sa.String(length=253), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column(
        'first_seen_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column(
        'last_seen_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_incident_type', 'incident', ['incident_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_incident_type')
    op.drop_table('incident')
    # ### end Alembic commands ###
