"""add incident_context table

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-18 17:30:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | Sequence[str] | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_context',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('context_type', sa.String(length=32), nullable=False),
    sa.Column('context_payload', sa.JSON(), nullable=False),
    sa.Column(
        'collected_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_context_incident_id', 'incident_context', ['incident_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_context_incident_id')
    op.drop_table('incident_context')
    # ### end Alembic commands ###
