"""add diagnostic_report table

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-18 17:35:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_report',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('diagnostic_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column(
        'executed_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diagnostic_report_diagnostic_type', 'diagnostic_report', ['diagnostic_type'])
    op.create_index('ix_diagnostic_report_cluster_id', 'diagnostic_report', ['cluster_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diagnostic_report_cluster_id')
    op.drop_index('ix_diagnostic_report_diagnostic_type')
    op.drop_table('diagnostic_report')
    # ### end Alembic commands ###
