apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentinel-agent.fullname" . }}-config
  labels:
    {{- include "sentinel-agent.labels" . | nindent 4 }}
data:
  SENTINEL_AGENT_NAME: sentinel-agent
  SENTINEL_AGENT_VERSION: {{ .Chart.AppVersion }}
  SENTINEL_AGENT_CLUSTER_NAME: {{ .Values.agent.clusterName }}
  SENTINEL_AGENT_ENVIRONMENT: {{ .Values.agent.environment }}
  SENTINEL_SENTINEL_API_URL: {{ .Values.sentinel.apiUrl }}
  SENTINEL_SENTINEL_MOCK_MODE: {{ .Values.sentinel.mockMode | quote }}
  SENTINEL_HEARTBEAT_INTERVAL_SECONDS: {{ .Values.heartbeat.intervalSeconds | quote }}
  SENTINEL_RUNTIME_LOG_LEVEL: INFO
  SENTINEL_STORAGE_DATABASE_URL: {{ .Values.storage.databaseUrl }}
  SENTINEL_TRANSPORT_ENABLED: {{ .Values.collection.transport.enabled | quote }}
  SENTINEL_TRANSPORT_BASE_URL: {{ .Values.collection.transport.baseUrl }}
  SENTINEL_TRANSPORT_MOCK_MODE: {{ .Values.collection.transport.mockMode | quote }}
  SENTINEL_COLLECTION_ENABLED: {{ .Values.collection.enabled | quote }}
  SENTINEL_COLLECTION_MAX_EVENTS: {{ .Values.collection.maxEvents | quote }}
