apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentinel-agent.fullname" . }}-config
  labels:
    {{- include "sentinel-agent.labels" . | nindent 4 }}
data:
  SENTINEL_AGENT_NAME: sentinel-agent
  SENTINEL_AGENT_VERSION: {{ .Chart.AppVersion }}
  SENTINEL_AGENT_CLUSTER_NAME: {{ .Values.agent.clusterName }}
  SENTINEL_AGENT_ENVIRONMENT: {{ .Values.agent.environment }}
  SENTINEL_SENTINEL_API_URL: {{ .Values.sentinel.apiUrl }}
  SENTINEL_SENTINEL_MOCK_MODE: {{ .Values.sentinel.mockMode | quote }}
  SENTINEL_HEARTBEAT_INTERVAL_SECONDS: {{ .Values.heartbeat.intervalSeconds | quote }}
  SENTINEL_RUNTIME_LOG_LEVEL: INFO
  SENTINEL_STORAGE_DATABASE_URL: {{ .Values.storage.databaseUrl }}
