apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel-agent.fullname" . }}-secret
  labels:
    {{- include "sentinel-agent.labels" . | nindent 4 }}
type: Opaque
data:
  sentinel-registration-token: {{ .Values.sentinel.registrationToken | b64enc }}
